name: ETL Infra CI/CD pipeline

on:
  push:
    branches: ["main"]
    paths: ["**.tf", "**.tfvars"]
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_location: "South Africa North"  # Override variables.tf
  TF_IN_AUTOMATION: true

jobs:
  deploy:
    name: Azure ETL CI/CD pipeline
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write  # For OIDC (recommended over client secrets)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan || exit 1
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "PLAN_SUMMARY<<$EOF" >> $GITHUB_OUTPUT
          terraform show -no-color tfplan >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false tfplan